// Generated by CoffeeScript 1.6.3
var greeting, job, name, num, obj, one, range, three, two, _i, _ref, _results;

name = "Jemery";

greeting = "Hello, " + name + "!";

console.log(greeting);

range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

console.log(range);

range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

console.log(range);

range = (function() {
  _results = [];
  for (_i = 50; _i > 10; _i--){ _results.push(_i); }
  return _results;
}).apply(this);

console.log(range);

obj = {
  name: "Jemery",
  job: "Programmer"
};

console.log(obj);

name = "John";

job = "Programmer";

obj = {
  name: name,
  job: job
};

console.log(obj);

_ref = ["1", "2", "3"], one = _ref[0], two = _ref[1], three = _ref[2];

console.log(two);

console.log(three);

name = "Jemery";

obj = {
  name: name,
  job: "Programmer",
  other: name
};

console.log(obj);

num = 10;

console.log(num + 1);
