// Generated by CoffeeScript 1.6.3
var exec;

exec = require('child_process').exec;

task('compile', 'Compiles all the .coffee files in src/ directory', function() {
  return exec('coffee -c -o js src/*.coffee');
});

task('watch', 'Watches for changes and recompiles the coffee files', function() {
  return exec('coffee -c -w -o js src/*.coffee');
});
