// Generated by CoffeeScript 1.6.3
var giveWork, greet, machine, name, person, person1, person2;

name = "Jim";

if (name === "Jeremy") {
  console.log(name);
} else if (name === "Jim") {
  console.log("Hi " + name);
} else {
  console.log("What is your name?");
}

name = "Jeremy";

if (name === "Jeremy") {
  console.log(name);
} else if (name === "Jim") {
  console.log("Hi " + name);
} else {
  console.log("What is your name?");
}

machine = {
  running: false,
  turnOn: function() {
    return this.running = true;
  }
};

if (!machine.running) {
  machine.turnOn();
}

console.log(machine.running);

person = {
  name: "Jeremy",
  job: "Programmer"
};

giveWork = function(person) {
  switch (person.job) {
    case "Programmer":
      return console.log("Here's your code work, " + person.name);
    case "Designer":
      return console.log("Here's your design work, " + person.name);
    default:
      return console.log("Um, do you work here ?");
  }
};

giveWork(person);

person1 = {
  name: "Jeremy",
  relationship: "Friend"
};

person2 = {
  name: "Jane",
  relationship: "Boss"
};

console.log("======== Way 1 =============");

greet = function(person) {
  if (person.relationship === "Friend") {
    return console.log("Hi, " + name + "!");
  } else if (person.relationship === "Boss") {
    return console.log("Hello, ma`am");
  }
};

greet(person1);

greet(person2);

console.log("======== Way 2 =============");

greet = function(person) {
  var msg;
  msg = person.relationship === "Friend" ? "Hi, " + name + "!" : person.relationship === "Boss" ? "Hello, ma`am" : void 0;
  return console.log(msg);
};

greet(person1);

greet(person2);

console.log("======== Way 3 =============");

greet = function(person) {
  return console.log(person.relationship === "Friend" ? "Hi, " + name + "!" : person.relationship === "Boss" ? "Hello, ma`am" : void 0);
};

greet(person1);

greet(person2);

console.log("======== Way 4 =============");

greet = function(person) {
  var msg;
  msg = (function() {
    switch (person.relationship) {
      case "Friend":
        return "Hi, " + name + "!";
      case "Boss":
        return "Hello, ma`am";
    }
  })();
  return console.log(msg);
};

greet(person1);

greet(person2);

/*
JS 
someVar = condition ? truthy : false

Coffee
someVar = if condition then truthy else falsey
*/

