// Generated by CoffeeScript 1.6.3
/* 
function greet (name) {
	console.log("Hello" + name "!");
}

greet = function (name) {
	
}
*/

var greet, greet_alternative, rand, test_end, test_middle, test_start,
  __slice = [].slice;

greet = function(name) {
  name = name || "friend";
  return "Hello " + name + "!";
};

greet_alternative = function(name) {
  if (name == null) {
    name = "friend";
  }
  return "Hello " + name + "!";
};

console.log(greet("CoffeeScript"));

console.log(greet());

console.log(greet_alternative("JS alternative"));

console.log(greet_alternative());

console.log("===== S T A R T =======");

test_start = function() {
  var x, y, z, _i;
  x = 3 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 2) : (_i = 0, []), y = arguments[_i++], z = arguments[_i++];
  console.log(x);
  console.log(y);
  return console.log(z);
};

test_start("one", "two", "three");

console.log("============");

test_start("one", "two", "three", "four", "five");

console.log("============");

test_start("one");

console.log("===== M I D D L E =======");

test_middle = function() {
  var x, y, z, _i;
  x = arguments[0], y = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), z = arguments[_i++];
  console.log(x);
  console.log(y);
  return console.log(z);
};

test_middle("one", "two", "three");

console.log("============");

test_middle("one", "two", "three", "four", "five");

console.log("===== E N D =======");

test_end = function() {
  var x, y, z;
  x = arguments[0], y = arguments[1], z = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
  console.log(x);
  console.log(y);
  return console.log(z);
};

test_end("one", "two", "three");

console.log("============");

test_end("one", "two", "three", "four", "five");

console.log("============");

test_end(["one", "two", "three", "four"]);

console.log("============");

test_end.apply(null, ["one", "two", "three", "four"]);

(function(message) {
  return console.log(message);
})("Hello");

rand = function(max, min) {
  if (max == null) {
    max = 10;
  }
  if (min == null) {
    min = 0;
  }
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

console.log(rand());

console.log(rand(100));

console.log(rand(60, 50));
