// Generated by CoffeeScript 1.6.3
var Site, arr, i, key, obj, siteName, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m,
  __hasProp = {}.hasOwnProperty;

arr = ["Nettuts+", "Aettuts+", "Phototuts+", "Psdtuts+", "Cgtuts+", "Mobiletuts+"];

obj = {
  name: "Nettuts+",
  topic: "Web Development",
  editor: "Jeffrey Way"
};

console.log("===== For loop simple =====");

/*
for (var i = 0; i < arr.length; i++) {
	console.log(arr[i]);
}
*/


for (_i = 0, _len = arr.length; _i < _len; _i++) {
  siteName = arr[_i];
  console.log(siteName);
}

console.log("===== For loop simple print key =====");

for (i = _j = 0, _len1 = arr.length; _j < _len1; i = ++_j) {
  siteName = arr[i];
  console.log("" + i + ": " + siteName);
}

console.log("===== For loop simple print key + conditions =====");

for (i = _k = 0, _len2 = arr.length; _k < _len2; i = ++_k) {
  siteName = arr[i];
  if (siteName.indexOf("P") === 0) {
    console.log("" + i + ": " + siteName);
  }
}

console.log("===== For loop simple print key + change iteration step =====");

for (i = _l = 0, _len3 = arr.length; _l < _len3; i = _l += 2) {
  siteName = arr[i];
  console.log("" + i + ": " + siteName);
}

console.log("===== Comprehensions =====");

for (_m = 0, _len4 = arr.length; _m < _len4; _m++) {
  siteName = arr[_m];
  console.log(siteName);
}

console.log("===== Comprehensions Power =====");

console.log((function() {
  var _len5, _n, _results;
  _results = [];
  for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
    siteName = arr[_n];
    _results.push(siteName);
  }
  return _results;
})());

console.log((function() {
  var _len5, _n, _results;
  _results = [];
  for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
    siteName = arr[_n];
    _results.push(siteName.length);
  }
  return _results;
})());

console.log("===== For loop - objects =====");

for (key in obj) {
  value = obj[key];
  console.log("" + key + ": " + value);
}

console.log("===== For loop - objects and prototype =====");

for (key in obj) {
  value = obj[key];
  if (key !== "name") {
    console.log("" + key + ": " + value);
  }
}

console.log("===== For loop - objects and prototype =====");

/*
for (val in obj) {
	if (obj.hasOwnProperty(val)) {
		//
	}
}
*/


Site = function(name) {
  return this.name = name;
};

Site.prototype.topic = "Web Development";

obj = new Site("Nettuts+");

for (key in obj) {
  value = obj[key];
  console.log("" + key + ": " + value);
}

for (key in obj) {
  if (!__hasProp.call(obj, key)) continue;
  value = obj[key];
  console.log("" + key + ": " + value);
}

console.log("===== While loop =====");

i = 0;

while (arr[i]) {
  console.log(arr[i]);
  i++;
}

console.log("===== While loop - until =====");

i = 0;

while (i !== arr.length) {
  console.log(arr[i]);
  i++;
}

i = 0;

while (i !== arr.length) {
  console.log(arr[i++]);
}

console.log("===== Loop break =====");

i = 0;

while (true) {
  console.log(arr[i++]);
  if (!(i < arr.length)) {
    break;
  }
}
