// Generated by CoffeeScript 1.6.3
var BorderCollie, Dog, dog, dog2,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Dog = (function() {
  function Dog(name) {
    this.name = name;
  }

  Dog.prototype.growl = function() {
    return console.log('*growl*');
  };

  return Dog;

})();

BorderCollie = (function(_super) {
  __extends(BorderCollie, _super);

  function BorderCollie(name, tricks) {
    this.tricks = tricks != null ? tricks : [];
    BorderCollie.__super__.constructor.call(this, name);
  }

  BorderCollie.prototype.perfom = function(trick) {
    return console.log(__indexOf.call(this.tricks, trick) >= 0 ? "" + this.name + " is " + trick : '*whine*');
  };

  BorderCollie.prototype.growl = function(person) {
    if (person === this.master) {
      return console.log('*bark*');
    } else {
      return BorderCollie.__super__.growl.call(this);
    }
  };

  return BorderCollie;

})(Dog);

dog = new Dog('Rusty');

console.log(dog.name);

dog.growl();

dog2 = new BorderCollie('Oreo', ['playing dead', 'fetching a ball']);

dog2.master = 'Jeremy';

console.log(dog2.name);

dog2.perfom('playing dead');

dog2.perfom('catching a frisbee');

dog2.growl('Jeremy');

dog2.growl('Jim');
